// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1580488779);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1580488899);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1580510019);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1580510139);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1580488659);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1580488449);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1580489019);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 737280);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580488389);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{02644b64-6e5c-4951-a789-db0a4d75fa7e}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1580509863982");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1580511672982");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1580509996366");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1580513596366");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1580488391");
user_pref("browser.slowStartup.averageTime", 3077);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1580488390);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580488391890");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "8051399484d74b28a3bd6229760d8e5d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 28 Jan 2020 10:28:50 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1580488779);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"631e67f2-5d43-46b9-82f0-69bff64e9096\",\"formautofill@mozilla.org\":\"cf3eef4d-0f6c-4d1b-a18c-e662948f44af\",\"screenshots@mozilla.org\":\"05f2ac39-bbcd-48dc-88af-b5d0c629452d\",\"webcompat-reporter@mozilla.org\":\"fb55048a-ef92-49d3-a65d-0b2747c41e44\",\"webcompat@mozilla.org\":\"9656a72c-78c8-4eae-b200-0ef080ff59be\",\"default-theme@mozilla.org\":\"e2fa9ac9-ced9-4926-92e8-25501d0e5b6c\",\"google@search.mozilla.org\":\"a6de0935-38e2-487a-971b-0bfecfb8c8ff\",\"amazondotcom@search.mozilla.org\":\"cba10f62-f65a-4bc0-a8af-589b6b961fce\",\"bing@search.mozilla.org\":\"e34031ce-230d-4a27-87bc-99b59a8fe0cc\",\"ddg@search.mozilla.org\":\"3bcbf671-b2b7-404e-99f3-aa5118554ed8\",\"ebay@search.mozilla.org\":\"695eb7c7-f6fa-4773-891a-952a4c2030f1\",\"twitter@search.mozilla.org\":\"cdcccf18-4b62-433e-988a-73a83e524829\",\"wikipedia@search.mozilla.org\":\"db66e7f2-b9ad-47f7-8596-199ed4237621\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1580488588);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1580488430);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200117190643");
user_pref("media.gmp-manager.lastCheck", 1580488429);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1580488588);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "107c326c-96fb-46d4-99ea-36e1101dd982");
user_pref("security.sandbox.plugin.tempDirSuffix", "b8887fe1-e8f1-496f-91c9-7198e3c82998");
user_pref("services.blocklist.pinning.checked", 1580488436);
user_pref("services.settings.clock_skew_seconds", -298);
user_pref("services.settings.last_etag", "\"1580463706578\"");
user_pref("services.settings.last_update_seconds", 1580488956);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1580488436);
user_pref("services.settings.main.cfr-fxa.last_check", 1580488436);
user_pref("services.settings.main.cfr.last_check", 1580488436);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1580488436);
user_pref("services.settings.main.hijack-blocklists.last_check", 1580488436);
user_pref("services.settings.main.language-dictionaries.last_check", 1580488436);
user_pref("services.settings.main.public-suffix-list.last_check", 1580488436);
user_pref("services.settings.main.sites-classification.last_check", 1580488436);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1580488436);
user_pref("services.settings.main.whats-new-panel.last_check", 1580488436);
user_pref("services.settings.security.onecrl.checked", 1580488436);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1580488588);
user_pref("toolkit.startup.last_success", 1580488387);
user_pref("toolkit.telemetry.cachedClientID", "da947609-a1b3-41f0-a7dd-b0cd26c1cbc6");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
